import BottomNavbar from "@/src/components/BottomNavbar";
import Navbar from "@/src/components/Navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            {children}
            <BottomNavbar />
        </div>
    );
}
